live_config_reload = true

[colors.bright]
black = "0x5b5858"
blue = "0x3fc4de"
cyan = "0x6be4e6"
green = "0x3fdaa4"
magenta = "0xf075b5"
red = "0xec6a88"
white = "0xd5d8da"
yellow = "0xfbc3a7"

[colors.normal]
black = "0x16161c"
blue = "0x26bbd9"
cyan = "0x59e1e3"
green = "0x29d398"
magenta = "0xee64ac"
red = "0xe95678"
white = "0xd5d8da"
yellow = "0xfab795"

[colors.primary]
background = "0x1c1e26"
foreground = "0xe0e0e0"

[cursor.style]
blinking = "on"
shape = "Block"

[font]
size = 10

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 1000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "none"
dynamic_title = true
opacity = 1

[window.padding]
x = 8
y = 8
